swagger: '2.0'
info:
  description: Sample suggestion for Argent Bank API's transactions model. Check  my [Argent Bank Frontend repository](https://github.com/pyleglise/ArgentBankFront)
  version: 1.0.0
  title: Bank Argent API transaction documentation
  termsOfService: http://swagger.io/terms/
  contact:
    { 'email': 'contact@axialdata.com', 'url': 'https://www.axialdata.com' }
host: localhost:3001
basePath: /api/v1
tags:
  - name: Transactions
    description: All the user's transaction
  - name: Transaction
    description: One specific transaction
  - name: Categories
    description: All the transaction's categories
schemes:
  - https
paths:
  /user/account/{accountId}:
    get:
      tags:
        - Transactions
      summary: User's transactions for the current month
      description: Get user's current month transactions
      operationId: getTransactionsByAccountId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Authorization Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: Account ID
          required: true
          type: number
        - name: Dates
          in: body
          description: Transaction's period to get
          required: true
          schema:
            $ref: '#/definitions/TransactionsDate'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ResponseTransactions'
        '400':
          description: Invalid account ID supplied
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
  /user/categories:
    get:
      tags:
        - Categories
      summary: Transaction's categories
      description: Get the transaction's categories
      operationId: getCategoriesByTransactionId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Autorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ResponseCategories'
        '400':
          description: Invalid transaction Id supplied
        '404':
          description: Category not found
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
  /user/transaction/{transactionId}:
    get:
      tags:
        - Transaction
      summary: Transaction details
      description: Get the chosen transaction's details
      operationId: getTransactionById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Authorization Bearer JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          description: Transaction ID
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ResponseDetails'
        '400':
          description: Invalid transaction Id supplied
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
    put:
      tags:
        - Transaction
      summary: Update the current transaction
      description: Update the current transaction's category
      operationId: upDateTransactionById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          description: Authorization Bearer JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          description: Transaction ID
          required: true
          type: string
        - name: Category
          in: body
          description: Update transaction's category
          required: true
          schema:
            $ref: '#/definitions/EditableDetails'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ResponseDetails'
        '400':
          description: Invalid transaction Id supplied
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
      security:
        - Bearer: []
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  ResponseTransactions:
    type: object
    properties:
      status:
        type: integer
        format: int64
        example: 200
      message:
        type: string
        format: string
        example: 'success : transactions fetched'
      body:
        type: array
        items:
          $ref: '#/definitions/Informations'
    xml:
      name: Transactions
  ResponseDetails:
    type: object
    properties:
      status:
        type: integer
        format: int64
        example: 200
      message:
        type: string
        format: string
        example: "success : transaction's detail fetched"
      schema:
        $ref: '#/definitions/Details'
    xml:
      name: Details
  ResponseCategories:
    type: object
    properties:
      status:
        type: integer
        format: int64
        example: 200
      message:
        type: string
        format: string
        example: "success : transaction's category fetched"
      schema:
        $ref: '#/definitions/Categories'
    xml:
      name: Details
  Informations:
    type: object
    properties:
      transactionId:
        type: string
        description: Transaction ID
        example: 95126657891626454894
      date:
        type: string
        format: date-time
        description: transaction date
        example: '2023-02-18T08:24:56.234Z'
      description:
        type: string
        description: transaction description
        example: Golden Sun Bakery
      amount:
        type: integer
        format: int64
        description: transaction amount
        example: 5
      balance:
        type: integer
        format: int64
        description: account balance after transaction
        example: 2082.79
    xml:
      name: Transaction
  Categories:
    type: array
    items:
      $ref: '#/definitions/Category'
    xml:
      name: Categories
  Details:
    type: object
    properties:
      transactionId:
        type: string
        description: Transaction ID
        example: 95126657891626454894
      type:
        type: string
        description: Transaction type
        example: Restaurant
      category:
        type: string
        description: transaction category
        example: Leasure
      notes:
        type: string
        description: transaction notes
        example: >-
          Out with the friends
    xml:
      name: Category
  EditableDetails:
    type: object
    properties:
      category:
        type: string
        description: Transaction name
      notes:
        type: string
        description: Transaction notes
    xml:
      name: TransactionDetails
  TransactionsDate:
    type: object
    properties:
      from:
        type: string
        format: date
        description: start date of period to get
        example: '2023-03-18'
      to:
        type: string
        format: date
        description: end date of period to get
        example: '2023-04-18'
    xml:
      name: TransactionsDate
  Category:
    type: string
    enum:
      - Leasure
      - Food
      - Lodging
      - Mobility
      - Energy
      - Supplies
      - Holidays
      - Other
